#!/usr/bin/env python3
"""
Phase B5: Populate non-esa_programs JSONB column from research directory.

Reads the non-ESA programs directory JSON and maps it into the states table
as non_esa_programs[] — parallel to esa_programs but for non-ESA funding
(tax credits, vouchers, scholarships, allotments, EFTC).

Usage:
    python3 populate-non-esa-programs.py              # full run
    python3 populate-non-esa-programs.py --dry-run     # preview only
    python3 populate-non-esa-programs.py --json path   # custom JSON path

Rollback: psql "$DATABASE_URL_ADMIN" -f ../drizzle/rollback-b5-non-esa.sql
"""

import json
import os
import sys

# ── Paths ──────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_JSON = "/home/ichabod/.hermes/cache/documents/doc_d4b1c5b2a287_non-esa-programs-directory.json"

# Env file path
ENV_PATH = "/opt/homeschool-compass/.env"


# ── Program type mapping ───────────────────────────────────────────────────
PROGRAM_TYPE_MAP = {
    "allotment": "allotment",
    "deduction": "deduction",
    "refundable_tax_credit": "refundable_tax_credit",
    "non_refundable_tax_credit": "non_refundable_tax_credit",
    "voucher": "voucher",
    "scholarship": "scholarship",
    "tuitioning": "tuitioning",
    "efct": "efct",
    "pending": "pending",
}


# ── Status derivation ──────────────────────────────────────────────────────
def derive_status(entry: dict) -> str:
    """Derive program status from research data."""
    pt = entry.get("program_type", "")
    notes = (entry.get("notes") or "").lower()

    if "expired" in notes or "duufunded" in notes or "sunset" in notes:
        return "expired"
    if "vetoed" in notes or "not available" in notes:
        return "blocked"
    if pt == "pending" or "proposed" in notes or "not (yet|passed|law)" in notes:
        return "proposed"
    if "defunct" in notes or "effectively defunded" in notes:
        return "defunct"
    if "come" in notes and ("2027" in notes or "future" in notes):
        return "pending_launch"
    return "active"


# ── Map directory entry → NonEsaProgram ────────────────────────────────────
def entry_to_program(entry: dict) -> dict:
    ptype = entry.get("program_type", "other")
    mapped_type = PROGRAM_TYPE_MAP.get(ptype, "other")

    return {
        "name": entry.get("program_name", ""),
        "program_type": mapped_type,
        "amount": entry.get("amount"),
        "income_cap": entry.get("income_cap"),
        "homeschool_eligible": bool(entry.get("homeschool_eligible", False)),
        "url": entry.get("url"),
        "application_url": None,
        "short_description": entry.get("short_description"),
        "application_method": entry.get("application_method"),
        "application_window": entry.get("application_window"),
        "stacks_with": entry.get("stacks_with"),
        "notes": entry.get("notes"),
        "status": derive_status(entry),
    }


# ── Group entries by state ─────────────────────────────────────────────────
def group_by_state(data: list) -> dict[str, list[dict]]:
    states = {}
    for entry in data:
        st = entry.get("state", "")
        states.setdefault(st, []).append(entry_to_program(entry))
    return states


# ── Build SQL ──────────────────────────────────────────────────────────────
def build_sql(states_programs: dict[str, list[dict]]) -> list[str]:
    sql = [
        "-- Phase B5: Populate non_esa_programs from research directory",
        "-- Generated by populate-non-esa-programs.py",
        "",
    ]
    for state_code in sorted(states_programs):
        programs = states_programs[state_code]
        json_str = json.dumps(programs, ensure_ascii=False)
        # Escape single quotes for SQL
        json_escaped = json_str.replace("'", "''")
        sql.append(
            f"UPDATE states "
            f"SET non_esa_programs = '{json_escaped}'::jsonb, "
            f"non_esa_verified_at = NOW() "
            f"WHERE code = '{state_code}';"
        )
    return sql


# ── Main ───────────────────────────────────────────────────────────────────
def main():
    dry_run = "--dry-run" in sys.argv

    json_path = DEFAULT_JSON
    for i, arg in enumerate(sys.argv):
        if arg == "--json" and i + 1 < len(sys.argv):
            json_path = sys.argv[i + 1]

    # Load JSON
    if not os.path.exists(json_path):
        print(f"ERROR: JSON not found at {json_path}")
        sys.exit(1)

    with open(json_path) as f:
        data = json.load(f)

    # Group
    state_groups = group_by_state(data)
    print(f"Loaded {len(data)} program entries across {len(state_groups)} states\n")

    # Summary
    total_hs = 0
    for st in sorted(state_groups):
        progs = state_groups[st]
        hs = sum(1 for p in progs if p["homeschool_eligible"])
        total_hs += hs
        types = [p["program_type"] for p in progs]
        print(f"  {st}: {len(progs)} programs, {hs} homeschool-eligible — {types}")
    print(f"\nTotal: {len(state_groups)} states, {len(data)} programs ({total_hs} homeschool-eligible)")

    # Dry run or execute
    sql_lines = build_sql(state_groups)

    if dry_run:
        print("\n─── SQL Preview ───")
        for line in sql_lines:
            print(line)
        print("\n─── END ───")
        return

    # Execute
    dsn = None
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH) as f:
            for line in f:
                if line.startswith("DATABASE_URL_ADMIN="):
                    dsn = line.strip().split("=", 1)[1]
                    break

    if not dsn:
        dsn = os.environ.get("DATABASE_URL_ADMIN")

    if not dsn:
        print("ERROR: No DATABASE_URL_ADMIN found in .env or environment")
        sys.exit(1)

    import psycopg2

    conn = psycopg2.connect(dsn)
    conn.autocommit = True
    cur = conn.cursor()

    for state_code in sorted(state_groups):
        programs = state_groups[state_code]
        json_str = json.dumps(programs, ensure_ascii=False)
        cur.execute(
            "UPDATE states SET non_esa_programs = %s::jsonb, non_esa_verified_at = NOW() WHERE code = %s",
            (json_str, state_code),
        )
        print(f"  ✓ {state_code}: {len(programs)} programs updated")

    cur.close()
    conn.close()
    print(f"\n✅ Done. {len(state_groups)} states populated.")


if __name__ == "__main__":
    main()
